networks:
  app_network:
    driver: bridge
services:
  db:
    image: mysql:8.0.42
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: pokemon_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network


  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3006:3006"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - app_network


  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:3006
    depends_on:
      - backend

volumes:
  mysql-data: